ignore = ["test/reference32", "test/reference64"]
format_markdown = true
style = "blue"
join_lines_based_on_source = true
annotate_untyped_fields_with_any = false
normalize_line_endings = "unix"
always_use_return = false # https://github.com/domluna/JuliaFormatter.jl/issues/888
align_assignment = true
align_struct_field = true
align_conditional = true
align_pair_arrow = true